### ISSUE TITLE
Task Creation Modal

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#127]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add a task creation modal that asks for name, description, date, and time

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by allenshen13** [comment]
Hey, I'm the other student from the University of Michigan. Can you assign this to us?

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
