### ISSUE TITLE
(JS-0422) Avoid `target='_blank'` attribute without `rel='noopener noreferrer'`

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#137]
## Description
When creating a JSX element with a tag, it is often desired to have the link open in a new tab using the `target=&#x27;_blank&#x27;` attribute. Using this attribute unaccompanied by `rel=&#x27;noreferrer&#x27;`, however, is a severe security vulnerability.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0422/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0422/occurrences/)

**Comment by jyo142** [comment]
Hi @raspberri05 can i take this issue as well?

**Comment by raspberri05** [comment]
Yes! I'll go ahead and assign you to it!
