### ISSUE TITLE
(JS-0356) Found unused variables in TypeScript code

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#139]
## Description
Unused variables are generally considered a code smell and should be avoided.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0356/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0356/occurrences/)

**Comment by Abdulaziz-Mirsagatov** [comment]
#176 
For this one I removed unused React imports from NavBar and Footer in addition to the unused variables specified in the issue
