### ISSUE TITLE
(JS-0454) Found invalid characters in markup

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#141]
## Description
The issue is raised because of missing or unescaped JSX escape characters. These characters would be injected as a text node in JSX statements, which might not be intentional. These won&#x27;t throw any syntax or runtime errors, but the rendered output will not be the same as expected.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0454/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0454/occurrences/)

**Comment by Abdulaziz-Mirsagatov** [comment]
Could you assign this to me? Also, I can see some other issues in the feed that I am interested in taking. Do I need to ask to be assigned to those issues before starting working on them or can I just make pull requests?

**Comment by raspberri05** [comment]
You can feel free to start working on any of the unassigned issues without asking to be assigned first. However, it would be great if you could comment on the issues you are working on so that I can assign you to that issue so that other people do not work on the same issue

**Comment by Abdulaziz-Mirsagatov** [comment]
The following PR was created - #174
