### ISSUE TITLE
dark mode/light mode toggle

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#149]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Create a simple toggle in settings to switch between light mode, dark mode, or system setting. Save this selection to user info in database. 

**Describe alternatives you've considered**
Possibly a third-party library for this

**Additional context**
n/a

**Comment by rbaronia108** [comment]
Hey! We are a pair of students taking a software engineering course at the University of Michigan, and would love to help contribute. Could you please assign this to us? Thanks!

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready.
