### ISSUE TITLE
Client-side task sorting

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#159]
**Is your feature request related to a problem? Please describe.**
In a list of tasks, when a task is completed by clicking the check mark, it remains in its current position and does not move below the uncompleted tasks, but intuitively it should

**Describe the solution you'd like**
Implement a simple stateful function on the client side to sort the task by whether the `completed` variable is false or true

**Describe alternatives you've considered**
n/a

**Additional context**
The sorting should be client-side only, should not at all involve the server

**Comment by taiyou1116** [comment]
Hello😄
nice to meet you!

May I take charge of this matter?
I will let you know if there is any progress!

**Comment by taiyou1116** [comment]
I have a question.

Will it be returned to its original location if it is marked incomplete again?
Should I return it to the bottom of the incomplete list or to the top?

What should I do?

**Comment by taiyou1116** [comment]
#164

**Comment by raspberri05** [comment]
Hi! Thanks for opening this issue and creating a pull request with a fix! I'll review it shortly.
