### ISSUE TITLE
Implement account deletion feature

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#163]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Implement the feature for a user to delete their account

**Describe alternatives you've considered**
n/a

**Additional context**
There is already a button for this in the settings tab, but the feature has not been implemented yet.

**Comment by ovodela** [comment]
Hey! I'm a student taking a software engineering course at the University of Michigan, and would love to help contribute. Could you please assign this to me? Thanks!

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.

**Comment by ayelet326** [comment]
Hi, I'm a student and I'd love to try to contribute,Thanks!

**Comment by ovodela** [comment]
Hi, I've got this issue covered but there are plenty of other issues in the repository that you could address

**Comment by raspberri05** [comment]
> Hi, I'm a student and I'd love to try to contribute,Thanks!

Hi! Looks like someone else is assigned to this issue already, but please feel free to work on any of the other unassigned issues in this repository  if you would like.  Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
