### ISSUE TITLE
[BUG] Disable AI mode is not persistent

### ISSUE THREAD

**Issue by ovodela** [raspberri05/taskorial#165]
**Describe the bug**
Disable AI mode is not persistent

**To Reproduce**
1. Create an account
2. Click on Disable AI Mode slider (should now say Enable AI mode and turn blue
3. Refresh the page or click on the home button at the top left
4. Slider automatically reset to default Disable AI Mode

**Expected behavior**
Disabling AI mode should be persistent

**Desktop**
 - OS: MacOS 14.4.1
 - Browser Chrome
 - Version 123.0.6312.107 (Official Build) (arm64)

**Additional context**

**Comment by raspberri05** [comment]
Hi! Thanks for opening the issue. The best way to fix this would probably be to store the state of the AI toggle as a field in the user info that is stored in the database. Feel free to work on this and open a pull request if you would like. If not, me or another contributor can work on it instead. Thanks.

**Comment by ovodela** [comment]
Sounds good i'm definitely interested in working on this. If you could also assign this to me that would be great.
