### ISSUE TITLE
User Feedback Form UI

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#180]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Create the UI/client side code for a simple feedback form where users can submit feedback about Taskorial. Should have a field for name, email, and feedback

**Describe alternatives you've considered**
third-party form embed or netlify forms could be alternatives

**Additional context**
n/a

**Comment by raspberri05** [comment]
I can assign you to this! I think just a simple form is ok - I don't it having to become more complicated later on which is why I think just creating the form component in-house would be best. Thanks

**Comment by jyo142** [comment]
Hello @raspberri05 sorry for the late pr

https://github.com/raspberri05/taskorial/pull/199

Do you already know what to do onsubmit of the form? I left that blank with a TODO

**Comment by raspberri05** [comment]
No worries, I'll take a look at it soon. For the form submission, I will add a backend route that emails me the details of the user feedback. Thanks for working on this.

**Comment by raspberri05** [comment]
closed with merged pr
