### ISSUE TITLE
separate server routes

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#184]
separate the server file that has all the server routes into multiple files that have routes grouped by category. Not sure how to do this, any help would be great

**Comment by Puskar-Roy** [comment]
hey @raspberri05, I'd like to tackle this issue of refactoring the server file into separate files for categorized routes.
Proposed Directory Structure:
controllers: This directory will house files representing individual controllers, categorized by their purpose.
for example controllers: authController.js, aiController.js, etc.
routes: This directory will contain route files for each controller for example routes: authRoutes.js, aiRoutes.js, etc.
Could you please assign this to me?
Thank You

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
