### ISSUE TITLE
Implement change email feature

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#185]
**Is your feature request related to a problem? Please describe.**
Users cannot change their account email address

**Describe the solution you'd like**
Implement the feature to allow users to change email (there is a button scaffolding in the settings page for this) 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sirteddi** [comment]
Heyho, I wanna help out, if that's alright :))

**Comment by MichaelAAwah** [comment]
i'm willing to work on the client side (i.e creating the form and integration) if anyone is available to work on the server side endpoints please let me know

**Comment by raspberri05** [comment]
I went ahead and assigned you both to this issue. Feel free to submit your changes via pull requests once you are ready. 
@MichaelAAwah, if you want to work on the client side, maybe @sirteddi, you would be willing to work on the server side? 
Also, please consider starring this repository as it will enable more developers to find and contribute to this project.

**Comment by MichaelAAwah** [comment]
@sirteddi Please let me know when you're done so that i can do the integration

**Comment by sirteddi** [comment]
@MichaelAAwah will do, probably this weekend

**Comment by sirteddi** [comment]
@MichaelAAwah sadly I just saw the server side code is written only in JavaScript – which I do not know entirely. I would have written it in TypeScript. Therefore I will have to give this to someone else – I am sorry.

**Comment by raspberri05** [comment]
@MichaelAAwah if you're willing to work on the server side code as well that would be great. If not, I or someone else can work on the server side code and then you can integrate it.
