### ISSUE TITLE
Make request data button open a new email to support@taskorial.com in user's mail client with subject and body line prefilled

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#187]
This will probably utilize a mailto property in an href attribute

**Comment by Pujan-sarkar** [comment]
hey @raspberri05 i want to contribute in your project , can you please explain me this issue in details .

**Comment by raspberri05** [comment]
Hi! Unfortunately, this issue is deprecated and will not need to be worked on. You may work on any of the other open and unassigned issues if you would like. Also, please consider starring this repository as it will enable more developers to find and contribute to this project. Thanks
