### ISSUE TITLE
(JS-0417, react-auth) Avoid `.bind()` or local functions in JSX properties

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#216]
## Description
Using `.bind()` or passing local callback functions as props to react component incurs a performance overhead. Consider using `React.useCallback`, or if possible, moving the callback definition outside the component. **EXCEPTIONS:** This rule may not apply if your react component is only rendered once, or if your application is not performance …

## Occurrences
There are 27 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0417/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0417/occurrences/)

**Comment by hemantsinghhere** [comment]
I want to work on this issue and I am pretty sure that i can handle this task.

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
