### ISSUE TITLE
(JS-0323, react-auth) Detected usage of the `any` type

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#218]
## Description
The `any` type can sometimes leak into your codebase. TypeScript compiler skips the type checking of the `any` typed variables, so it creates a potential safety hole, and source of bugs in your codebase. We recommend using `unknown` or `never` type variable.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0323/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-0323/occurrences/)

**Comment by ravishxt** [comment]
Can you assign this to me?

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
