### ISSUE TITLE
(JS-D1001, react-auth) Documentation comments not found for functions and classes

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#220]
## Description
It is recommended to have documentation comments above, or right inside a function/class declaration. This helps developers, users and even the author understand the purpose of a code snippet or API function in the future. **NOTE**: If you want to stop this issue from getting raised on certain constructs (arrow …

## Occurrences
There are 30 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-D1001/occurrences/](https://app.deepsource.com/gh/raspberri05/taskorial:react-auth/issue/JS-D1001/occurrences/)

**Comment by franceslonsdale** [comment]
Hi would it be possible for me to get assigned this?

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready.
