### ISSUE TITLE
Developer mode toggle hangs on form submit

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#224]
**Describe the bug**
With developer mode on, if you submit a task, the toggle switches to the off position until the task is fully created, but the toggle label does not change at all

**To Reproduce**
see above

**Expected behavior**
Task submission should not change toggle state

**Comment by TalhaBinNasir** [comment]
Hi @raspberri05, i think the issue is with form reset when form is submitted. I can fix it. Can you assign me this issue?

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
