### ISSUE TITLE
Full buttons not clickable on settings page

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#225]
**Describe the bug**
You have to click on the button text to activate the buttons on the settings page

**To Reproduce**
see above

**Expected behavior**
You should be able to click anywhere on the buttons to activate it.

**Comment by TalhaBinNasir** [comment]
Hi @raspberri05, could you assign me this issue?

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready.

**Comment by raspberri05** [comment]
I saw your PR and will review it soon
