### ISSUE TITLE
Task completion bug with duplicate task

### ISSUE THREAD

**Issue by sharadChauhan7** [raspberri05/taskorial#237]
**Describe the bug**
if we add two or more similar tasks then once you marked them checked you can not uncheck them only one duplicate task gets toggled.

**To Reproduce**
1. Go to 'dashboad'
2. Add two or more same tasks
3. Then mark them as done
4. Then try to uncheck(here is the bug)

**Expected behavior**
Should be able to toggle mark as done feature on duplicate tasks also

https://github.com/raspberri05/taskorial/assets/103198852/678ec4a6-b4dc-4c28-9643-a5b0a067f4b2

**Comment by raspberri05** [comment]
Hi, thanks for flagging this bug! Please let me know if you would like to work on a fix so I can assign you to this issue. If not, no worries, I or someone else can work on the fix. Thanks

**Comment by sharadChauhan7** [comment]
I would be happy to work on a fix for this issue. Please feel free to assign it to me. Thanks!

**Comment by raspberri05** [comment]
I've assigned you to this issue :)
