### ISSUE TITLE
Adding tutorial video to Getting Started Page

### ISSUE THREAD

**Issue by franceslonsdale** [raspberri05/taskorial#252]
**Is your feature request related to a problem? Please describe.**
It's not a big issue but when I tried to go through the getting started instructions I struggled to follow them and it took me a while as it followed some unfamiliar concepts so I had to do quite a bit of research just to set the Taskorial repo on my computer so I thought adding a video would make this clear and easy as it's all in one place.

**Describe the solution you'd like**
I would like to add the YouTube video I creates with the link posted below which clones the repo onto your device and then follows the getting started instructions.
https://www.youtube.com/watch?v=dwKfQmmdDPU

**Describe alternatives you've considered**
I decided thought about adding a more in detail file of instructions with images for people who haven't had much experience with TypeScript and Git up however I personally I find it much easier to follow a YouTube video as this is where I found all my solutions to setting it up hence I made the YouTube video

**Additional context**
It's just a YouTube video on my account which I made public just as an extra to the Getting Started page

**Comment by raspberri05** [comment]
Thanks for raising this issue! I'll take a look at the video you have created soon and add it to the "Getting Started" page of rhe Taskorial wiki. I am also in the process of updating the wiki and rewriting the Getting Started page, so hopefully that will make things easier for people.

**Comment by raspberri05** [comment]
I looked at the video and it seemed great! I went ahead and added it to the repository documentation and credited you for creating it as well!
