### ISSUE TITLE
force email validation on account creation

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#89]
**Is your feature request related to a problem? Please describe.**
Account emails are only validated for structure - it is not checked whether it is an active email address that belongs to the user

**Describe the solution you'd like**
Force email validation on account creation, most likely via third party or nodemailer

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by aarjun8060** [comment]
would you assign this issue to me ?
