### ISSUE TITLE
refactor task creation call from client to not fetch entire task list

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/taskorial#91]
After a task is created on the client side, a get tasks request is sent from the client to re-get and display all the tasks after creating the new task. This needs refactoring so that after the creation of the task in the server, the task should just be added to the user's task list on the client side instead of fetching the entire task list from the server again.

**Comment by raspberri05** [comment]
Hi! Thanks for pointing that out, and what you are saying seems correct. If you would like to work on this issue please let me know.

**Comment by ravishxt** [comment]
Yes, please assign this to me.

**Comment by raspberri05** [comment]
done
