### ISSUE TITLE
Disable the sign up form button while creating the account

### ISSUE THREAD

**Issue by anmoljhamb** [raspberri05/taskorial#97]
**Is your feature request related to a problem? Please describe.**
It is a bit frustrating when you don't know if something is happening or not. 

**Describe the solution you'd like**
To basically create a loading state, so that, we can set it to true or false, and accordingly disable the button. 

**Describe alternatives you've considered**
We could use a framework like react query, but it honestly seems to be over kill, for only two buttons right now.

**Comment by anmoljhamb** [comment]
Hey! I'd like to work on this issue! I'll add this feature for both the login and sign up buttons.

**Comment by raspberri05** [comment]
Hi! Thanks for opening an issue for this, and feel free to work on this issue and open a pull request :). I would definitely agree that the sign-in / sign-up page is not the most user-friendly right now and there isn't really any feedback to know if something is happening or not. If you have an idea on how to better implement the sign in/sign up flow as a whole please feel free to suggest changes for that as well. Once you open a pull request, it would be great if you could include a couple of screenshots of the changes just so I can better understand the changes. Thanks :)

**Comment by raspberri05** [comment]
Also, if there is anything that is confusing within the set up documentation please feel free to let me know and I can help you resolve it and so I can improve the documentation :)

**Comment by anmoljhamb** [comment]
Sure! I'll definitely ask if I face any issues.
