### ISSUE TITLE
Site is re-rendered on opening the NavLinks

### ISSUE THREAD

**Issue by anmoljhamb** [raspberri05/taskorial#99]
**Describe the bug**
Whenever a user clicks on the Navbar Links, i.e. Login and Sign Up, or even the redirection after the login and signup, the page gets re-rendered. We are using react-router-dom, so, we should use the features along with it. If we just wrap the text content in login and signup with the Link tag from react-router-dom, our website would no longer be re-rendered. And similarly, just use the useNavigate hook to redirect after a user is logged in, or signs up.

**To Reproduce**
1. Just click on a navbar link

**Expected behavior**
The content of the routes should just be replaced, instead of the entire application, re-rendering.

**Comment by anmoljhamb** [comment]
Hey! any update?

**Comment by raspberri05** [comment]
Hi! Sorry about my late response. Feel free to work on these changes/open a pull request. Thanks!

**Comment by raspberri05** [comment]
Hi @anmoljhamb . Just wanted to follow up to see if you still wanted to work on this.

**Comment by Somu878** [comment]
Hi @raspberri05 ,
I Would happy to fix this, please assign this to me

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.

**Comment by Somu878** [comment]
@raspberri05  please review my PR

**Comment by raspberri05** [comment]
Thanks for opening a PR! I'll review it soon
